### ISSUE TITLE
Workspace Project View Does Not Automatically Detect Added or Removed Files

### ISSUE THREAD

**Issue by curtjen** [TweakStyle/BetaFeedback#37]
The Workspace view has the ability to view the default sample project and the ability to create new projects. However, when creating files in the project's directory outside of Tweakstyle, the files do not automatically show up in the project's file list on the Workspace tab. Only after restarting Tweakstyle does the project's list update.

**Comment by felicienfrancois** [comment]
Implemented in TweakStyle 0.7.0
