### ISSUE TITLE
Add Or Remove Version Number From Open With Menu

### ISSUE THREAD

**Issue by mikebronner** [TweakStyle/BetaFeedback#54]
On the Mac, the version number seems to be an empty string, as it displays with parentheses but no number in the Open With window:

![screen shot 2014-10-23 at 8 20 17 am](https://cloud.githubusercontent.com/assets/1791050/4755768/2a06c3c6-5ac8-11e4-9809-1c0aff57c783.png)

**Comment by felicienfrancois** [comment]
Fixed in last release 0.6.0
