### ISSUE TITLE
Selected elements are inactive

### ISSUE THREAD

**Issue by anselme16** [TweakStyle/BetaFeedback#62]
When a clickable/hoverable/etc element is selected with the selection tool, it will not create any event.

This bug is reproducible on any link, select the <a></a> area with the selector tool, try to click the link, nothing happens.

I believe it is not the expected behavior, if it is, what is the best way to deselect an area ?

**Comment by felicienfrancois** [comment]
Fixed in TweakStyle 0.7.0
